---
deployment:
  tasks:
    # Define la ruta destino
    - export DEPLOYPATH=/home/drclzsib/public_html/drinout-backend

    # Define carpeta temporal
    - export TEMPDIR=/home/drclzsib/tmp/deploy-temp

    # Crea carpeta temporal si no existe
    - /bin/mkdir -p $TEMPDIR

    # Sincroniza código a carpeta temporal, excluyendo .env
    - /bin/rsync -a --delete --exclude=".env" ./ $TEMPDIR/

    # Sincroniza temporal con destino, excluyendo .env
    - /bin/rsync -a --delete --exclude=".env" $TEMPDIR/ $DEPLOYPATH/

    # Crea venv si no existe
    - if [ ! -d "$DEPLOYPATH/venv" ]; then /usr/bin/python3 -m venv $DEPLOYPATH/venv; fi

    # Activa venv e instala dependencias
    - source $DEPLOYPATH/venv/bin/activate && pip install --upgrade pip && pip install -r $DEPLOYPATH/requirements.txt

    # Reinicia Passenger (si aplica)
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
