version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: drinout_db
    environment:
      MARIADB_ROOT_PASSWORD: "root_password"
      MARIADB_DATABASE: "my_database"
      MARIADB_USER: "my_user"
      MARIADB_PASSWORD: "my_password"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    restart: always

  drinout:
    build: .
    container_name: drinout
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      PYTHON_VERSION: "3.11"
      DB_HOST: "mariadb"
      DB_USER: "my_user"
      DB_PASSWORD: "my_password"
      DB_NAME: "my_database"
      SECRET_KEY: "mysuperawesome"
      JWT_SECRET_KEY: "jwtawesometoken"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mariadb_data:
