version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MARIADB_ROOT_PASSWORD: "root_password"
      MARIADB_DATABASE: "my_database"
      MARIADB_USER: "my_user"
      MARIADB_PASSWORD: "my_password"
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    restart: always

volumes:
  mariadb_data:
