services:
  drinout:
    build: .
    container_name: drinout
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    environment:
      FLASK_APP: "main.py"
      FLASK_ENV: "development"
    command: flask run --host=0.0.0.0 --port=5000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
